FROM node:20-slim AS base
WORKDIR /app
RUN apt-get update -y && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm install
COPY . .
ENV PRISMA_CLI_BINARY_TARGETS="linux-arm64-openssl-3.0.x"
RUN npx prisma generate
EXPOSE 5000
CMD ["npm", "start"]